on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
      - uses: actions/checkout@main

      # Install dependencies for each target
      - name: Install dependencies for Linux (musl)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config

      # - name: Install dependencies for Windows (gnu)
      #   if: matrix.target == 'x86_64-pc-windows-gnu'
      #   run: |
      #     choco install <windows_package_1>
      #     choco install <windows_package_2>

      # - name: Install dependencies for macOS (darwin)
      #   if: matrix.target == 'x86_64-apple-darwin'
      #   run: |
      #     brew install <mac_package_1>
      #     brew install <mac_package_2>

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
